# This file is included as a package in all mmwave presence sensors
# I use the Bermuda BLE Trilateration integration.  I set the area
# on devices that include this beacon.yaml file using the ESPHome
# integration.
#
esphome:
  comment: "Beacon"

# System time config - required for precise timestamps, used in integration:
time:
  - platform: homeassistant
    id: homeassistant_time

bluetooth_proxy:

